### ISSUE TITLE
Error: No route to host: 192.168.2.216:8443

### ISSUE THREAD

**Issue by yarisvt** [TheMrBooyah/hassio-dirigera-client#15]
Hello,

I have succesfully retrieved the token using 
```bash
java -jar dirigera-client-dump.jar --dirigera.hostname=192.168.1.216 --dirigera.port=8443
```

However, when I try to run the add-on in HomeAssistant with the following config:

```yml
dirigera_host: 192.168.2.216
mqtt_host: core-mosquitto
port: 1883
username: mosquitto
password: password
token: >-
  My_TOKEN
```

I get the following error:
```
2023-07-11 21:37:02.238  INFO 66 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Start event handler thread: id=21, name=boundedElastic-1
2023-07-11 21:37:02.251 ERROR 66 --- [or-http-epoll-6] d.d.i.dirigera.client.api.WebSocketApi   : Error while listening to websocket events: finishConnect(..) failed: No route to host: /192.168.2.216:8443
```

I am not sure what I am doing wrong?
